### ISSUE TITLE
Specifying different accounts with the same cloud provider

### ISSUE THREAD

**Issue by see-quick** [redhat-cop/osia#38]
As a user, I would like to specify different accounts on the same cloud provider. The main for such change is because these two accounts could provide various differences (f.e., networks). 

This is currently supported:
```yaml
default:
  cloud:
    aws:
      ....
      list_of_regions: [ ]
    openstack:
      ...
      network_list: [ ]
  ...
```
And I would like to have more accounts on the same cloud provider, where I will be able to specify different settings resulting with:
```yaml
default:
  cloud:
    aws:
      ....
      list_of_regions: [ ]
    openstack:
      ...
      network_list: 
         - great_network_1
         - not_so_good_network_10
         - ...
     ...
    second-openstack:
     ... 
       network_list: 
          - n1
          - n2
          - ...
  ...
```
