### ISSUE TITLE
Route53 configuration

### ISSUE THREAD

**Issue by azgabur** [redhat-cop/osia#91]
I would like to define path to aws credentials file for route53 dns the same way as nsupdate key_file is defined in `settings.yaml`. Currently I have to use env variable `AWS_SHARED_CREDENTIALS_FILE` to achieve this result - if I do not want to use the default location.
```
default:
  dns:
    route53:
       credentials_file: "path/to/file"
```

**Comment by azgabur** [comment]
Helpful docs: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

**Comment by mdujava** [comment]
AWS credentials are required also for deploying clusters to aws. So such declaration would make sense to have also in cloud  
```
default:
  cloud:
    aws:
      environments:
      - name: default
        credentials_file: "path/to/file"
```
